direction: right
x: {
  label: slacker
  icon: cli.svg
  shape: image
}

y: {
  label: slack
  icon: https://icons.terrastruct.com/dev%2Fslack.svg
  shape: image
}

z: {
  label: happiness
  icon: https://www.svgrepo.com/show/128297/happiness.svg
  shape: image
}

x -> y -> z
